require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - ./rubocop/cop/style/redundant_keyword.rb

AllCops:
  TargetRubyVersion: 3.5
  NewCops: enable
  SuggestExtensions: true

Layout/ArgumentAlignment:
  Enabled: false
  Autocorrect: false

Layout/LineLength:
  Enabled: false
  Autocorrect: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Autocorrect: false
  Max: 30

Metrics/ClassLength:
  Enabled: true
  Autocorrect: false

Metrics/MethodLength:
  Enabled: true
  Autocorrect: false
  Max: 20

Naming/AccessorMethodName:
  Enabled: true
  Autocorrect: false

Style/Documentation:
  Enabled: false
  Autocorrect: false

Style/FrozenStringLiteralComment:
  Enabled: false
  Autocorrect: false

Style/MutableConstant:
  Enabled: false
  Autocorrect: false

Style/NumericPredicate:
  Enabled: true
  Autocorrect: true
