services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: brandcrunchbot_web
    working_dir: /rails
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/rails:cached
      - ~/.config/pry/pryrc:/rails/.pryrc:ro
      - ~/.config/guard/Guardfile:/rails/Guardfile:ro
    environment:
      - REDIS_URL=redis://redis:6379/0
      - INSIDE_DOCKER=true
      - TERM=xterm-256color
      - DISPLAY=${DISPLAY}
      - UID=1000
      - GID=1000
      - BUY_IT_NOW_COUNTER=10
      - BUY_IT_NOW_SLEEP=0.5
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - brandcrunchbot_network

  db:
    image: postgres:latest
    container_name: brandcrunchbot_db
    environment:
      POSTGRES_USER: brandcrunchbot
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - brandcrunchbot_network

  redis:
    image: redis:latest
    container_name: brandcrunchbot_redis
    volumes:
      - redis_data:/data
    networks:
      - brandcrunchbot_network
    ports:
      - "6379:6379"

networks:
  brandcrunchbot_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
