# Use the Ruby base image
FROM ruby:latest

# Set the working directory inside the container
WORKDIR /rails

# Install dependencies needed for Rails (optional)
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

# Copy Gemfile and Gemfile.lock to the container
COPY Gemfile ./

# Install Bundler and gems
RUN gem install bundler && bundle install 



# Copy the rest of the application code
COPY . .

# Expose port 3000 for the Rails server
EXPOSE 3000

# Run the Rails server
CMD ["bash", "-c", "bundle exec rails server -b 0.0.0.0"]
