# Use the Ruby base image
FROM ruby:3.4.4

# Install dependencies needed for Rails
RUN apt-get update -qq && apt-get install -y \
  nodejs \
  postgresql-client

# Set working directory inside container
WORKDIR /rails

# Copy entrypoint script
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh

# Set entrypoint
ENTRYPOINT ["entrypoint.sh"]

# Expose port for Rails server
EXPOSE 3000

# Default command
CMD ["bash", "-c", "bundle exec rails server -b 0.0.0.0"]

