require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/finish_details", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FinishDetail. As you add validations to FinishDetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FinishDetail.create! valid_attributes
      get finish_details_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      finish_detail = FinishDetail.create! valid_attributes
      get finish_detail_url(finish_detail)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_finish_detail_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      finish_detail = FinishDetail.create! valid_attributes
      get edit_finish_detail_url(finish_detail)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FinishDetail" do
        expect {
          post finish_details_url, params: { finish_detail: valid_attributes }
        }.to change(FinishDetail, :count).by(1)
      end

      it "redirects to the created finish_detail" do
        post finish_details_url, params: { finish_detail: valid_attributes }
        expect(response).to redirect_to(finish_detail_url(FinishDetail.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FinishDetail" do
        expect {
          post finish_details_url, params: { finish_detail: invalid_attributes }
        }.to change(FinishDetail, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post finish_details_url, params: { finish_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested finish_detail" do
        finish_detail = FinishDetail.create! valid_attributes
        patch finish_detail_url(finish_detail), params: { finish_detail: new_attributes }
        finish_detail.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the finish_detail" do
        finish_detail = FinishDetail.create! valid_attributes
        patch finish_detail_url(finish_detail), params: { finish_detail: new_attributes }
        finish_detail.reload
        expect(response).to redirect_to(finish_detail_url(finish_detail))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        finish_detail = FinishDetail.create! valid_attributes
        patch finish_detail_url(finish_detail), params: { finish_detail: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested finish_detail" do
      finish_detail = FinishDetail.create! valid_attributes
      expect {
        delete finish_detail_url(finish_detail)
      }.to change(FinishDetail, :count).by(-1)
    end

    it "redirects to the finish_details list" do
      finish_detail = FinishDetail.create! valid_attributes
      delete finish_detail_url(finish_detail)
      expect(response).to redirect_to(finish_details_url)
    end
  end
end
