default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: brandcrunchbot_development

test:
  <<: *default
  database: brandcrunchbot_test

production:
  <<: *default
  database: brandcrunchbot_production
  url: <%= ENV['DATABASE_URL'] %>
